[package]
name = "df-test-dogfood"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
df-test-github = { path = "../df-test-github" }
df-test-protocol = { path = "../df-test-protocol" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
